# Generated by Django 5.2.1 on 2025-05-18 13:27

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(help_text='Client name', max_length=255)),
                ('numero_fiscal', models.CharField(help_text='Fiscal registration number', max_length=255, unique=True)),
                ('adresse', models.CharField(blank=True, help_text='Client address', max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, help_text='Client phone number', max_length=20, null=True, validators=[api.models.validate_phone])),
                ('nom_responsable', models.CharField(blank=True, help_text="Manager or responsible person's name", max_length=255, null=True)),
                ('email', models.EmailField(blank=True, help_text="Client's email", max_length=254, null=True, validators=[api.models.validate_email])),
                ('email_responsable', models.EmailField(blank=True, help_text="Manager or responsible person's email", max_length=254, null=True, validators=[api.models.validate_email])),
                ('telephone_responsable', models.CharField(blank=True, help_text="Manager or responsible person's phone number", max_length=20, null=True, validators=[api.models.validate_phone])),
                ('autre_numero', models.CharField(blank=True, help_text='Other optional number', max_length=20, null=True, validators=[api.models.validate_phone])),
                ('informations_complementaires', models.TextField(blank=True, help_text='Additional information about the client', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date when the client was created')),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True, help_text='Date when the client was last updated')),
            ],
            options={
                'ordering': ['nom_client'],
                'indexes': [models.Index(fields=['nom_client'], name='api_client_nom_cli_13517d_idx'), models.Index(fields=['numero_fiscal'], name='api_client_numero__695cd6_idx')],
            },
        ),
    ]
