# Generated by Django 5.2.1 on 2025-06-03 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantraite',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.client'),
        ),
        migrations.AlterField(
            model_name='plantraite',
            name='facture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.facturetravaux'),
        ),
        migrations.AlterField(
            model_name='plantraite',
            name='status',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('PAYEE', 'Payée')], default='EN_COURS', max_length=20),
        ),
        migrations.AlterField(
            model_name='traite',
            name='date_echeance',
            field=models.DateField(help_text="Date d'échéance"),
        ),
        migrations.AlterField(
            model_name='traite',
            name='montant',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traite',
            name='plan_traite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traites', to='api.plantraite'),
        ),
        migrations.AlterField(
            model_name='traite',
            name='status',
            field=models.CharField(choices=[('NON_PAYEE', 'Non payée'), ('PAYEE', 'Payée')], default='NON_PAYEE', max_length=20),
        ),
    ]
