# Generated by Django 5.2.1 on 2025-08-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='produit',
            name='api_produit_prix_14e5c5_idx',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='code_produit',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='epaisseur',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='largeur',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='longueur',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='prix',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='surface',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='type_matiere',
        ),
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.CharField(blank=True, help_text='Main product category', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='code_barres',
            field=models.CharField(blank=True, help_text='Product barcode', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='emplacement',
            field=models.CharField(blank=True, help_text='Storage location', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='fournisseur',
            field=models.CharField(blank=True, help_text='Supplier of the product', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='materiau',
            field=models.CharField(blank=True, help_text='Material of the product', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_achat',
            field=models.FloatField(blank=True, help_text='Purchase price of the product', null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_vente',
            field=models.FloatField(blank=True, help_text='Selling price of the product', null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='ref_produit',
            field=models.CharField(default=0, help_text='Reference code for the product', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='seuil_alerte',
            field=models.PositiveIntegerField(default=0, help_text='Stock alert threshold'),
        ),
        migrations.AddField(
            model_name='produit',
            name='sous_categorie',
            field=models.CharField(blank=True, help_text='Sub-category of the product', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('supprime', 'Supprimé')], default='actif', help_text='Product status', max_length=50),
        ),
        migrations.AddField(
            model_name='produit',
            name='stock_initial',
            field=models.PositiveIntegerField(default=0, help_text='Initial stock quantity'),
        ),
        migrations.AddField(
            model_name='produit',
            name='unite_mesure',
            field=models.CharField(blank=True, help_text='Unit of measurement (e.g., kg, m, piece)', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['ref_produit'], name='api_produit_ref_pro_ab347e_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['prix_vente'], name='api_produit_prix_ve_f7942b_idx'),
        ),
    ]
