# Generated by Django 5.2.1 on 2025-05-18 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_matiere', models.CharField(choices=[('acier', 'Acier'), ('acier_inoxydable', 'Acier inoxydable'), ('aluminium', 'Aluminium'), ('laiton', 'Laiton'), ('cuivre', 'Cuivre'), ('acier_galvanise', 'Acier galvanisé'), ('autre', 'Autre')], default='autre', help_text='Material type', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Material description', null=True)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, help_text='Unit price of the material', max_digits=10)),
                ('quantite_en_stock', models.PositiveIntegerField(default=0, help_text='Quantity in stock')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date when the material was created')),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True, help_text='Date when the material was last updated')),
                ('client', models.ForeignKey(help_text='Client', on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(help_text='Product name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Product description', null=True)),
                ('prix', models.DecimalField(decimal_places=2, help_text='Product price', max_digits=10)),
                ('quantite_en_stock', models.PositiveIntegerField(default=0, help_text='Quantity in stock')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date when the product was created')),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True, help_text='Date when the product was last updated')),
            ],
            options={
                'ordering': ['nom_produit'],
                'indexes': [models.Index(fields=['nom_produit'], name='api_produit_nom_pro_f2b30d_idx'), models.Index(fields=['prix'], name='api_produit_prix_14e5c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Traveaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree', models.PositiveIntegerField(help_text='Duration of the work in hours')),
                ('description', models.TextField(blank=True, help_text='Work description', null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_cours', help_text='Work status', max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date when the work was created')),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True, help_text='Date when the work was last updated')),
                ('client', models.ForeignKey(help_text='Client', on_delete=django.db.models.deletion.CASCADE, related_name='travaux', to='api.client')),
                ('produit', models.ForeignKey(help_text='Product', on_delete=django.db.models.deletion.CASCADE, related_name='travaux', to='api.produit')),
            ],
            options={
                'indexes': [models.Index(fields=['client'], name='api_traveau_client__1deb58_idx'), models.Index(fields=['produit'], name='api_traveau_produit_5f4d87_idx'), models.Index(fields=['duree'], name='api_traveau_duree_cc4907_idx')],
            },
        ),
    ]
