# Generated by Django 5.2.1 on 2025-06-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatierePremiereAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=100, unique=True)),
                ('nom_matiere', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('metaux', 'Métaux'), ('fixation', 'Fixation'), ('plastique', 'Plastique'), ('autre', 'Autre')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('unite_mesure', models.CharField(choices=[('kg', 'Kilogramme'), ('pcs', 'Pièce'), ('m2', 'Mètre carré'), ('m3', 'Mètre cube')], max_length=10)),
                ('remaining_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_minimum', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('emplacement', models.CharField(blank=True, max_length=200, null=True)),
                ('fournisseur_principal', models.CharField(max_length=200)),
                ('prix_unitaire', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date_reception', models.DateField()),
                ('ref_fournisseur', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='devis',
            name='timbre_fiscal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Timbre fiscal'),
        ),
        migrations.AddField(
            model_name='plantraite',
            name='acceptance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantraite',
            name='bank_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantraite',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plantraite',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plantraite',
            name='notice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantraite',
            name='rip',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
