# Generated by Django 5.2.1 on 2025-08-29 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='stock_initial',
            new_name='stock',
        ),
    ]
