# Generated by Django 5.2.1 on 2025-05-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_matiere_produit_traveaux'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveaux',
            name='statut',
        ),
        migrations.AddField(
            model_name='traveaux',
            name='quantite',
            field=models.FloatField(default=1, help_text='Quantity of the product used for the work'),
        ),
    ]
