# Generated by Django 5.2.1 on 2025-06-27 21:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_matierepremiereachat_devis_timbre_fiscal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='facture',
        ),
        migrations.AddField(
            model_name='cd',
            name='bons',
            field=models.ManyToManyField(blank=True, help_text='Liste des bons liés à cette commande', related_name='commandes_associees', to='api.facturetravaux'),
        ),
        migrations.AddField(
            model_name='cd',
            name='type_facture',
            field=models.CharField(default='', help_text='Product or Bon invoice'),
        ),
        migrations.AddField(
            model_name='commande',
            name='type_facture',
            field=models.CharField(default='', help_text='Product or Bon invoice'),
        ),
        migrations.AddField(
            model_name='matierepremiereachat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matierepremiereachat',
            name='epaisseur',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Épaisseur en mm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='matierepremiereachat',
            name='largeur',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Largeur en mètres', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='matierepremiereachat',
            name='longueur',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Longueur en mètres', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='matierepremiereachat',
            name='surface',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Surface en m²', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cd',
            name='facture',
            field=models.OneToOneField(blank=True, help_text='Associated invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande_associee', to='api.facturetravaux'),
        ),
        migrations.AlterField(
            model_name='matierepremiereachat',
            name='categorie',
            field=models.CharField(choices=[('acier', 'Acier'), ('acier_inoxydable', 'Acier inoxydable'), ('aluminium', 'Aluminium'), ('laiton', 'Laiton'), ('cuivre', 'Cuivre'), ('acier_galvanise', 'Acier galvanisé'), ('autre', 'Autre')], default='autre', max_length=100),
        ),
        migrations.AlterField(
            model_name='matierepremiereachat',
            name='unite_mesure',
            field=models.CharField(choices=[('kg', 'Kilogramme'), ('pcs', 'Pièce'), ('m2', 'Mètre carré'), ('m3', 'Mètre cube')], default='kg', max_length=10),
        ),
    ]
