# Generated by Django 5.2.1 on 2025-05-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_traveaux_statut_traveaux_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='prix_unitaire',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Unit price of the material', max_digits=10, null=True),
        ),
    ]
