# Generated by Django 5.2.1 on 2025-05-19 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_matiere_prix_unitaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matiere',
            old_name='quantite_en_stock',
            new_name='quantite',
        ),
    ]
