# Generated by Django 5.2.1 on 2025-05-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_quantite_en_stock_matiere_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='remaining_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Remaining quantity after work'),
        ),
    ]
