# Generated by Django 5.2.1 on 2025-05-19 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_matiere_remaining_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatiereUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_utilisee', models.PositiveIntegerField(default=1, help_text='Quantity used in the work')),
                ('matiere', models.ForeignKey(help_text='Material', on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='api.matiere')),
                ('travaux', models.ForeignKey(help_text='Work', on_delete=django.db.models.deletion.CASCADE, related_name='matiere_usages', to='api.traveaux')),
            ],
            options={
                'unique_together': {('travaux', 'matiere')},
            },
        ),
        migrations.AddField(
            model_name='traveaux',
            name='matieres',
            field=models.ManyToManyField(help_text='Materials used', related_name='travaux', through='api.MatiereUsage', to='api.matiere'),
        ),
    ]
