# Generated by Django 5.2.1 on 2025-05-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_matiereusage_traveaux_matieres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='quantite_en_stock',
        ),
        migrations.AddField(
            model_name='matiere',
            name='epaisser',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Thickness of the material in mm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='matiere',
            name='longueur',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length of the material in mm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='matiere',
            name='surface',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Surface area of the material in m²', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='epaisseur',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Thickness of the product in mm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, help_text='Product image', null=True, upload_to='produits/'),
        ),
        migrations.AddField(
            model_name='produit',
            name='longueur',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length of the product in mm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='surface',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Surface area of the product in m²', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='type_matiere',
            field=models.CharField(choices=[('acier', 'Acier'), ('acier_inoxydable', 'Acier inoxydable'), ('aluminium', 'Aluminium'), ('laiton', 'Laiton'), ('cuivre', 'Cuivre'), ('acier_galvanise', 'Acier galvanisé'), ('autre', 'Autre')], default='autre', help_text='Material type', max_length=50),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Product price', max_digits=10, null=True),
        ),
    ]
