# Generated by Django 5.2.1 on 2025-05-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_produit_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True, help_text='Product description', null=True),
        ),
    ]
