# Generated by Django 5.2.1 on 2025-05-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_produit_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matiere',
            old_name='longueur',
            new_name='length',
        ),
        migrations.RenameField(
            model_name='matiere',
            old_name='epaisser',
            new_name='thickness',
        ),
        migrations.AddField(
            model_name='matiere',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Width of the material in mm', max_digits=10, null=True),
        ),
    ]
