# Generated by Django 5.2.1 on 2025-05-20 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_longueur_matiere_length_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactureTravaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(help_text='Invoice number', max_length=50, unique=True)),
                ('date_emission', models.DateField(help_text='Invoice generation date')),
                ('date_echeance', models.DateField(blank=True, help_text='Due date', null=True)),
                ('statut', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée'), ('paid', 'Payée'), ('cancelled', 'Annulée')], default='draft', help_text='Invoice status', max_length=20)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=20.0, help_text='Tax rate percentage', max_digits=5)),
                ('montant_ht', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount excluding tax', max_digits=10, null=True)),
                ('montant_tva', models.DecimalField(blank=True, decimal_places=2, help_text='Tax amount', max_digits=10, null=True)),
                ('montant_ttc', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount including tax', max_digits=10, null=True)),
                ('date_generated', models.DateTimeField(auto_now_add=True, help_text='Date when the invoice was generated')),
                ('notes', models.TextField(blank=True, help_text='Additional notes on the invoice', null=True)),
                ('conditions_paiement', models.TextField(blank=True, help_text='Payment terms and conditions', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True, help_text='Last update date')),
                ('client', models.ForeignKey(help_text='Client', on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='api.client')),
                ('travaux', models.ManyToManyField(help_text='Work items included in invoice', related_name='factures', to='api.traveaux')),
            ],
            options={
                'ordering': ['-date_emission', '-numero_facture'],
                'indexes': [models.Index(fields=['numero_facture'], name='api_facture_numero__127469_idx'), models.Index(fields=['client'], name='api_facture_client__af6848_idx'), models.Index(fields=['date_emission'], name='api_facture_date_em_eca237_idx'), models.Index(fields=['statut'], name='api_facture_statut_88c988_idx')],
            },
        ),
    ]
