# Generated by Django 5.2.1 on 2025-05-21 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_facturetravaux'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactureMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bon', models.CharField(help_text='Bon number', max_length=50, unique=True)),
                ('date_reception', models.DateField(help_text='Reception date')),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=20.0, help_text='Tax rate percentage', max_digits=5)),
                ('montant_ht', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount excluding tax', max_digits=10, null=True)),
                ('montant_tva', models.DecimalField(blank=True, decimal_places=2, help_text='Tax amount', max_digits=10, null=True)),
                ('montant_ttc', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount including tax', max_digits=10, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True, help_text='Last update date')),
                ('client', models.ForeignKey(help_text='Client', on_delete=django.db.models.deletion.CASCADE, related_name='bons_reception', to='api.client')),
                ('matieres', models.ManyToManyField(help_text='Received materials', related_name='bons_reception', to='api.matiere')),
            ],
            options={
                'ordering': ['-date_reception'],
                'indexes': [models.Index(fields=['numero_bon'], name='api_facture_numero__400f14_idx'), models.Index(fields=['client'], name='api_facture_client__2fe0e6_idx'), models.Index(fields=['date_reception'], name='api_facture_date_re_62e534_idx')],
            },
        ),
    ]
