# Generated by Django 5.2.1 on 2025-05-22 01:05

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_facturematiere'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(help_text="Nom de l'entreprise", max_length=255)),
                ('numero_fiscal', models.CharField(help_text='Fiscal registration number', max_length=255, unique=True)),
                ('adresse', models.CharField(blank=True, help_text='Entreprise address', max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, help_text='Entreprise phone number', max_length=20, null=True, validators=[api.models.validate_phone])),
                ('email', models.EmailField(blank=True, help_text="Entreprise's email", max_length=254, null=True, validators=[api.models.validate_email])),
                ('site_web', models.URLField(blank=True, help_text="Site web de l'entreprise", null=True)),
                ('logo', models.ImageField(blank=True, help_text="Logo de l'entreprise", null=True, upload_to='entreprises/')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='nom_raison_sociale',
            field=models.CharField(blank=True, help_text='Nom de la raison sociale', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PlanTraite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_traite', models.PositiveIntegerField(help_text='Number of traitements')),
                ('date_emission', models.DateField(auto_now_add=True, help_text='Invoice generation date')),
                ('status', models.CharField(choices=[('EN_COURS', 'En cours'), ('PAYEE', 'payée')], default='EN_COURS', help_text='Traite status', max_length=20)),
                ('date_premier_echeance', models.DateField(blank=True, help_text='Date of the first installment', null=True)),
                ('periode', models.PositiveIntegerField(blank=True, help_text='Period between each milking', null=True)),
                ('montant_total', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount', max_digits=10, null=True)),
                ('nom_raison_sociale', models.CharField(blank=True, help_text='Nom de la raison sociale', max_length=255, null=True)),
                ('matricule_fiscal', models.CharField(blank=True, help_text='Matricule fiscal', max_length=255, null=True)),
                ('facture', models.OneToOneField(help_text='Invoice', on_delete=django.db.models.deletion.CASCADE, to='api.facturetravaux')),
            ],
            options={
                'ordering': ['-date_emission', 'date_premier_echeance'],
            },
        ),
        migrations.CreateModel(
            name='Traite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_echeance', models.DateField(auto_now_add=True, help_text='Invoice generation date')),
                ('status', models.CharField(choices=[('NON_PAYEE', 'Non payée'), ('PAYEE', 'Payée')], default='NON_PAYEE', help_text='Traite status', max_length=20)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount', max_digits=10, null=True)),
                ('plan_traite', models.ForeignKey(help_text='Traite', on_delete=django.db.models.deletion.CASCADE, related_name='traites', to='api.plantraite')),
            ],
            options={
                'ordering': ['-date_echeance'],
            },
        ),
        migrations.AddIndex(
            model_name='plantraite',
            index=models.Index(fields=['facture'], name='api_plantra_facture_7d82de_idx'),
        ),
        migrations.AddIndex(
            model_name='plantraite',
            index=models.Index(fields=['date_emission'], name='api_plantra_date_em_3499d6_idx'),
        ),
        migrations.AddIndex(
            model_name='plantraite',
            index=models.Index(fields=['date_premier_echeance'], name='api_plantra_date_pr_3759b9_idx'),
        ),
        migrations.AddIndex(
            model_name='plantraite',
            index=models.Index(fields=['status'], name='api_plantra_status_5ca84c_idx'),
        ),
        migrations.AddIndex(
            model_name='traite',
            index=models.Index(fields=['plan_traite'], name='api_traite_plan_tr_725ba9_idx'),
        ),
        migrations.AddIndex(
            model_name='traite',
            index=models.Index(fields=['date_echeance'], name='api_traite_date_ec_bc277b_idx'),
        ),
        migrations.AddIndex(
            model_name='traite',
            index=models.Index(fields=['status'], name='api_traite_status_b44c8d_idx'),
        ),
    ]
