# Generated by Django 5.2.1 on 2025-05-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_entreprise_client_nom_raison_sociale_plantraite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='numero_bon',
            field=models.CharField(blank=True, help_text='Material reception number', max_length=50, null=True, unique=True),
        ),
    ]
