# Generated by Django 5.2.1 on 2025-05-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_matiere_numero_bon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturematiere',
            name='montant_ht',
            field=models.IntegerField(blank=True, help_text='Total amount excluding tax', null=True),
        ),
        migrations.AlterField(
            model_name='facturematiere',
            name='montant_ttc',
            field=models.IntegerField(blank=True, help_text='Total amount including tax', null=True),
        ),
        migrations.AlterField(
            model_name='facturematiere',
            name='montant_tva',
            field=models.IntegerField(blank=True, help_text='Tax amount', null=True),
        ),
        migrations.AlterField(
            model_name='facturematiere',
            name='tax_rate',
            field=models.IntegerField(default=20, help_text='Tax rate percentage'),
        ),
        migrations.AlterField(
            model_name='facturetravaux',
            name='montant_ht',
            field=models.IntegerField(blank=True, help_text='Total amount excluding tax', null=True),
        ),
        migrations.AlterField(
            model_name='facturetravaux',
            name='montant_ttc',
            field=models.IntegerField(blank=True, help_text='Total amount including tax', null=True),
        ),
        migrations.AlterField(
            model_name='facturetravaux',
            name='montant_tva',
            field=models.IntegerField(blank=True, help_text='Tax amount', null=True),
        ),
        migrations.AlterField(
            model_name='facturetravaux',
            name='tax_rate',
            field=models.IntegerField(default=20, help_text='Tax rate percentage'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='length',
            field=models.IntegerField(blank=True, help_text='Length of the material in mm', null=True),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='prix_unitaire',
            field=models.IntegerField(blank=True, help_text='Unit price of the material', null=True),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='surface',
            field=models.IntegerField(blank=True, help_text='Surface area of the material in m²', null=True),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='thickness',
            field=models.IntegerField(blank=True, help_text='Thickness of the material in mm', null=True),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='width',
            field=models.IntegerField(blank=True, help_text='Width of the material in mm', null=True),
        ),
        migrations.AlterField(
            model_name='plantraite',
            name='montant_total',
            field=models.IntegerField(blank=True, help_text='Total amount', null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='epaisseur',
            field=models.IntegerField(blank=True, help_text='Thickness of the product in mm', null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='longueur',
            field=models.IntegerField(blank=True, help_text='Length of the product in mm', null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.IntegerField(blank=True, help_text='Product price', null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='surface',
            field=models.IntegerField(blank=True, help_text='Surface area of the product in m²', null=True),
        ),
        migrations.AlterField(
            model_name='traite',
            name='montant',
            field=models.IntegerField(blank=True, help_text='Total amount', null=True),
        ),
    ]
