# Generated by Django 5.2.1 on 2025-05-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_facturematiere_montant_ht_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='reception_date',
            field=models.DateField(blank=True, help_text='Date of material reception', null=True),
        ),
    ]
