# Generated by Django 5.2.1 on 2025-05-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_matiere_reception_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='largeur',
            field=models.IntegerField(blank=True, help_text='Width of the product in mm', null=True),
        ),
    ]
