# Generated by Django 5.2.1 on 2025-05-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_produit_largeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturematiere',
            name='montant_ht',
            field=models.FloatField(blank=True, help_text='Total amount excluding tax', null=True),
        ),
        migrations.AlterField(
            model_name='facturematiere',
            name='montant_ttc',
            field=models.FloatField(blank=True, help_text='Total amount including tax', null=True),
        ),
        migrations.AlterField(
            model_name='facturematiere',
            name='montant_tva',
            field=models.FloatField(blank=True, help_text='Tax amount', null=True),
        ),
        migrations.AlterField(
            model_name='facturetravaux',
            name='montant_ht',
            field=models.FloatField(blank=True, help_text='Total amount excluding tax', null=True),
        ),
        migrations.AlterField(
            model_name='facturetravaux',
            name='montant_ttc',
            field=models.FloatField(blank=True, help_text='Total amount including tax', null=True),
        ),
        migrations.AlterField(
            model_name='facturetravaux',
            name='montant_tva',
            field=models.FloatField(blank=True, help_text='Tax amount', null=True),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='prix_unitaire',
            field=models.FloatField(blank=True, help_text='Unit price of the material', null=True),
        ),
        migrations.AlterField(
            model_name='plantraite',
            name='montant_total',
            field=models.FloatField(blank=True, help_text='Total amount', null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.FloatField(blank=True, help_text='Product price', null=True),
        ),
        migrations.AlterField(
            model_name='traite',
            name='montant',
            field=models.FloatField(blank=True, help_text='Total amount', null=True),
        ),
    ]
