# Generated by Django 5.2.1 on 2025-05-23 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_facturematiere_montant_ht_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonRetour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bon', models.CharField(help_text='Bon number', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée'), ('paid', 'Payée'), ('cancelled', 'Annulée')], default='draft', help_text='Bon status', max_length=20)),
                ('date_reception', models.DateField(help_text='Reception date')),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('tax_rate', models.IntegerField(default=20, help_text='Tax rate percentage')),
                ('montant_ht', models.FloatField(blank=True, help_text='Total amount excluding tax', null=True)),
                ('montant_tva', models.FloatField(blank=True, help_text='Tax amount', null=True)),
                ('montant_ttc', models.FloatField(blank=True, help_text='Total amount including tax', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True, help_text='Last update date')),
                ('date_retour', models.DateField(help_text='Return date')),
                ('date_emission', models.DateField(auto_now_add=True, help_text='Emission date')),
                ('client', models.ForeignKey(help_text='Client', on_delete=django.db.models.deletion.CASCADE, related_name='bons_retour', to='api.client')),
            ],
            options={
                'ordering': ['-date_retour', '-numero_bon'],
            },
        ),
        migrations.CreateModel(
            name='MatiereRetour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_retournee', models.PositiveIntegerField(default=1, help_text='Quantity of material returned')),
                ('bon_retour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matiere_retours', to='api.bonretour')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retours', to='api.matiere')),
            ],
            options={
                'unique_together': {('bon_retour', 'matiere')},
            },
        ),
        migrations.AddField(
            model_name='bonretour',
            name='matieres',
            field=models.ManyToManyField(help_text='Returned materials', related_name='bons_retour', through='api.MatiereRetour', to='api.matiere'),
        ),
        migrations.AddIndex(
            model_name='bonretour',
            index=models.Index(fields=['numero_bon'], name='api_bonreto_numero__f3a0ca_idx'),
        ),
        migrations.AddIndex(
            model_name='bonretour',
            index=models.Index(fields=['client'], name='api_bonreto_client__0774b2_idx'),
        ),
        migrations.AddIndex(
            model_name='bonretour',
            index=models.Index(fields=['date_retour'], name='api_bonreto_date_re_76c4e7_idx'),
        ),
        migrations.AddIndex(
            model_name='bonretour',
            index=models.Index(fields=['status'], name='api_bonreto_status_23c196_idx'),
        ),
    ]
