# Generated by Django 5.2.1 on 2025-05-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_bonretour_matiereretour_bonretour_matieres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonretour',
            name='montant_ht',
        ),
        migrations.RemoveField(
            model_name='bonretour',
            name='montant_ttc',
        ),
        migrations.RemoveField(
            model_name='bonretour',
            name='montant_tva',
        ),
        migrations.RemoveField(
            model_name='bonretour',
            name='tax_rate',
        ),
        migrations.AlterField(
            model_name='bonretour',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée'), ('completed', 'Complété'), ('cancelled', 'Annulée')], default='draft', help_text='Bon status', max_length=20),
        ),
    ]
