# Generated by Django 5.2.1 on 2025-05-23 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_bonretour_montant_ht_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_devis', models.CharField(help_text='Quote number', max_length=50, unique=True)),
                ('date_emission', models.DateField(help_text='Quote issue date')),
                ('date_validite', models.DateField(help_text='Quote validity date (15 days after issue)')),
                ('statut', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('accepted', 'Accepté'), ('rejected', 'Rejeté'), ('expired', 'Expiré'), ('converted', 'Converti en commande')], default='draft', help_text='Quote status', max_length=20)),
                ('tax_rate', models.IntegerField(default=20, help_text='Tax rate percentage')),
                ('montant_ht', models.FloatField(blank=True, help_text='Total amount excluding tax', null=True)),
                ('montant_tva', models.FloatField(blank=True, help_text='Tax amount', null=True)),
                ('montant_ttc', models.FloatField(blank=True, help_text='Total amount including tax', null=True)),
                ('remarques', models.TextField(default='Remarques :\n_ Validité du devis : 15 jours.\n_ Ce devis doit être accepté et signé pour valider la commande', help_text='Standard remarks on the quote')),
                ('notes', models.TextField(blank=True, help_text='Additional notes on the quote', null=True)),
                ('conditions_paiement', models.TextField(blank=True, help_text='Payment terms and conditions', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True, help_text='Last update date')),
                ('client', models.ForeignKey(help_text='Client', on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='api.client')),
            ],
            options={
                'ordering': ['-date_emission', '-numero_devis'],
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(help_text='Order number', max_length=50, unique=True)),
                ('date_commande', models.DateField(help_text='Order date')),
                ('date_livraison_prevue', models.DateField(blank=True, help_text='Expected delivery date', null=True)),
                ('date_livraison_reelle', models.DateField(blank=True, help_text='Actual delivery date', null=True)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('invoiced', 'Facturée')], default='pending', help_text='Order status', max_length=20)),
                ('tax_rate', models.IntegerField(default=20, help_text='Tax rate percentage')),
                ('montant_ht', models.FloatField(blank=True, help_text='Total amount excluding tax', null=True)),
                ('montant_tva', models.FloatField(blank=True, help_text='Tax amount', null=True)),
                ('montant_ttc', models.FloatField(blank=True, help_text='Total amount including tax', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes on the order', null=True)),
                ('conditions_paiement', models.TextField(blank=True, help_text='Payment terms and conditions', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True, help_text='Last update date')),
                ('client', models.ForeignKey(help_text='Client', on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='api.client')),
                ('facture', models.OneToOneField(blank=True, help_text='Associated invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande_associee', to='api.facturetravaux')),
                ('devis', models.OneToOneField(blank=True, help_text='Associated quote', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande', to='api.devis')),
            ],
            options={
                'ordering': ['-date_commande', '-numero_commande'],
            },
        ),
        migrations.CreateModel(
            name='ProduitCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1, help_text='Product quantity')),
                ('prix_unitaire', models.FloatField(blank=True, help_text='Unit price for this product', null=True)),
                ('remise_pourcentage', models.FloatField(default=0, help_text='Discount percentage')),
                ('prix_total', models.FloatField(blank=True, help_text='Total price for this product entry', null=True)),
                ('commande', models.ForeignKey(help_text='Order', on_delete=django.db.models.deletion.CASCADE, related_name='produit_commande', to='api.commande')),
                ('produit', models.ForeignKey(help_text='Product', on_delete=django.db.models.deletion.CASCADE, related_name='commande_produits', to='api.produit')),
            ],
            options={
                'unique_together': {('commande', 'produit')},
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='produits',
            field=models.ManyToManyField(help_text='Products included in order', related_name='commandes', through='api.ProduitCommande', to='api.produit'),
        ),
        migrations.CreateModel(
            name='ProduitDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1, help_text='Product quantity')),
                ('prix_unitaire', models.FloatField(blank=True, help_text='Unit price for this product', null=True)),
                ('remise_pourcentage', models.FloatField(default=0, help_text='Discount percentage')),
                ('prix_total', models.FloatField(blank=True, help_text='Total price for this product entry', null=True)),
                ('devis', models.ForeignKey(help_text='Quote', on_delete=django.db.models.deletion.CASCADE, related_name='produit_devis', to='api.devis')),
                ('produit', models.ForeignKey(help_text='Product', on_delete=django.db.models.deletion.CASCADE, related_name='devis_produits', to='api.produit')),
            ],
        ),
        migrations.AddField(
            model_name='devis',
            name='produits',
            field=models.ManyToManyField(help_text='Products included in quote', related_name='devis', through='api.ProduitDevis', to='api.produit'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['numero_commande'], name='api_command_numero__5b6cb5_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['client'], name='api_command_client__764faf_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['date_commande'], name='api_command_date_co_06309f_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['statut'], name='api_command_statut_8922d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='produitdevis',
            unique_together={('devis', 'produit')},
        ),
        migrations.AddIndex(
            model_name='devis',
            index=models.Index(fields=['numero_devis'], name='api_devis_numero__96fbf1_idx'),
        ),
        migrations.AddIndex(
            model_name='devis',
            index=models.Index(fields=['client'], name='api_devis_client__8f7099_idx'),
        ),
        migrations.AddIndex(
            model_name='devis',
            index=models.Index(fields=['date_emission'], name='api_devis_date_em_f363c2_idx'),
        ),
        migrations.AddIndex(
            model_name='devis',
            index=models.Index(fields=['statut'], name='api_devis_statut_89ceca_idx'),
        ),
    ]
