# Generated by Django 5.2.1 on 2025-05-24 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_devis_commande_produitcommande_commande_produits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date when the command was created')),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True, help_text='Date when the command was last updated')),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, help_text='Montant hors taxes', max_digits=10)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=19, help_text='Taux de TVA en pourcentage', max_digits=4)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, help_text='Montant de la TVA', max_digits=10)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, help_text='Montant toutes taxes comprises', max_digits=10)),
                ('client', models.ForeignKey(blank=True, help_text='Client', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commandes_produits', to='api.client')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.IntegerField(blank=True, help_text='Total amount', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date when the invoice was created')),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True, help_text='Date when the invoice was last updated')),
                ('commande', models.OneToOneField(help_text='Commande', on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='api.commandeproduit')),
            ],
        ),
        migrations.AlterField(
            model_name='plantraite',
            name='facture',
            field=models.OneToOneField(help_text='Invoice', on_delete=django.db.models.deletion.CASCADE, to='api.facture'),
        ),
        migrations.CreateModel(
            name='LineCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.IntegerField(blank=True, help_text='Product price', null=True)),
                ('quantite', models.PositiveIntegerField(default=1, help_text='Quantité')),
                ('prix_total', models.IntegerField(blank=True, help_text='Total price', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date when the command was created')),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True, help_text='Date when the command was last updated')),
                ('commande', models.ForeignKey(help_text='Commande', on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='api.commandeproduit')),
                ('produit', models.OneToOneField(help_text='Produit', on_delete=django.db.models.deletion.CASCADE, related_name='ligne', to='api.produit')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PaymentComptant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_PAID', 'Non payée'), ('PAID', 'Payée')], default='NOT_PAID', help_text='Payment status', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date when the payment was created')),
                ('montant', models.IntegerField(blank=True, help_text='Total amount', null=True)),
                ('facture', models.OneToOneField(help_text='Invoice', on_delete=django.db.models.deletion.CASCADE, to='api.facture')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddIndex(
            model_name='commandeproduit',
            index=models.Index(fields=['client'], name='api_command_client__8c0844_idx'),
        ),
        migrations.AddIndex(
            model_name='commandeproduit',
            index=models.Index(fields=['date_creation'], name='api_command_date_cr_60c21f_idx'),
        ),
        migrations.AddIndex(
            model_name='linecommande',
            index=models.Index(fields=['commande'], name='api_linecom_command_d5e1f1_idx'),
        ),
        migrations.AddIndex(
            model_name='linecommande',
            index=models.Index(fields=['produit'], name='api_linecom_produit_bb14f8_idx'),
        ),
        migrations.AddIndex(
            model_name='linecommande',
            index=models.Index(fields=['prix'], name='api_linecom_prix_904b9a_idx'),
        ),
        migrations.AddIndex(
            model_name='linecommande',
            index=models.Index(fields=['quantite'], name='api_linecom_quantit_583b64_idx'),
        ),
        migrations.AddIndex(
            model_name='linecommande',
            index=models.Index(fields=['prix_total'], name='api_linecom_prix_to_af2080_idx'),
        ),
        migrations.AddIndex(
            model_name='linecommande',
            index=models.Index(fields=['date_creation'], name='api_linecom_date_cr_5d741e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcomptant',
            index=models.Index(fields=['facture'], name='api_payment_facture_0d2921_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcomptant',
            index=models.Index(fields=['date_creation'], name='api_payment_date_cr_820f8b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcomptant',
            index=models.Index(fields=['status'], name='api_payment_status_39ed8a_idx'),
        ),
    ]
