# Generated by Django 5.2.1 on 2025-05-24 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_commandeproduit_facture_alter_plantraite_facture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(help_text='Order number', max_length=50, unique=True)),
                ('date_commande', models.DateField(help_text='Order date')),
                ('date_livraison_prevue', models.DateField(blank=True, help_text='Expected delivery date', null=True)),
                ('date_livraison_reelle', models.DateField(blank=True, help_text='Actual delivery date', null=True)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('invoiced', 'Facturée')], default='pending', help_text='Order status', max_length=20)),
                ('tax_rate', models.IntegerField(default=20, help_text='Tax rate percentage')),
                ('montant_ht', models.FloatField(blank=True, help_text='Total amount excluding tax', null=True)),
                ('montant_tva', models.FloatField(blank=True, help_text='Tax amount', null=True)),
                ('montant_ttc', models.FloatField(blank=True, help_text='Total amount including tax', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes on the order', null=True)),
                ('conditions_paiement', models.TextField(blank=True, help_text='Payment terms and conditions', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True, help_text='Last update date')),
                ('client', models.ForeignKey(help_text='Client', on_delete=django.db.models.deletion.CASCADE, related_name='cd', to='api.client')),
                ('devis', models.OneToOneField(blank=True, help_text='Associated quote', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cd', to='api.devis')),
                ('facture', models.OneToOneField(blank=True, help_text='Associated invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cd_associee', to='api.facturetravaux')),
            ],
            options={
                'ordering': ['-date_commande', '-numero_commande'],
            },
        ),
        migrations.CreateModel(
            name='PdC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1, help_text='Product quantity')),
                ('prix_unitaire', models.FloatField(blank=True, help_text='Unit price for this product', null=True)),
                ('remise_pourcentage', models.FloatField(default=0, help_text='Discount percentage')),
                ('prix_total', models.FloatField(blank=True, help_text='Total price for this product entry', null=True)),
                ('cd', models.ForeignKey(help_text='Order', on_delete=django.db.models.deletion.CASCADE, related_name='produit_cd', to='api.cd')),
                ('produit', models.ForeignKey(help_text='Product', on_delete=django.db.models.deletion.CASCADE, related_name='cd_produits', to='api.produit')),
            ],
            options={
                'unique_together': {('cd', 'produit')},
            },
        ),
        migrations.AddField(
            model_name='cd',
            name='produits',
            field=models.ManyToManyField(help_text='Products included in order', related_name='cd', through='api.PdC', to='api.produit'),
        ),
        migrations.AddIndex(
            model_name='cd',
            index=models.Index(fields=['numero_commande'], name='api_cd_numero__a29f4a_idx'),
        ),
        migrations.AddIndex(
            model_name='cd',
            index=models.Index(fields=['client'], name='api_cd_client__a76831_idx'),
        ),
        migrations.AddIndex(
            model_name='cd',
            index=models.Index(fields=['date_commande'], name='api_cd_date_co_0f3a4c_idx'),
        ),
        migrations.AddIndex(
            model_name='cd',
            index=models.Index(fields=['statut'], name='api_cd_statut_9d82d0_idx'),
        ),
    ]
