# Generated by Django 5.2.1 on 2025-05-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_cd_pdc_cd_produits_cd_api_cd_numero__a29f4a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd',
            name='mode_paiement',
            field=models.CharField(choices=[('traite', 'Traite'), ('cash', 'Comptant'), ('mixte', 'Mixte'), ('virement', 'Virement')], default='cash', help_text='Payment method', max_length=20),
        ),
    ]
