# Generated by Django 5.2.1 on 2025-05-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_cd_mode_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantraite',
            name='mode_paiement',
            field=models.CharField(choices=[('traite', 'Traite'), ('cash', 'Comptant'), ('mixte', 'Mixte'), ('virement', 'Virement')], default='traite', help_text='Payment method for the installment plan', max_length=20),
        ),
    ]
