# Generated by Django 5.2.1 on 2025-05-29 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_cd_mode_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd',
            name='timbre_fiscal',
            field=models.FloatField(blank=True, help_text='Fiscal stamp', null=True),
        ),
    ]
