# Generated by Django 5.2.1 on 2025-05-29 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_cd_timbre_fiscal'),
        ('api', '0025_plantraite_mode_paiement'),
    ]

    operations = [
    ]
