# Generated by Django 5.2.1 on 2025-05-29 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_merge_20250529_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdc',
            name='timbre_fiscal',
            field=models.FloatField(blank=True, help_text='Fiscal stamp for this product entry', null=True),
        ),
    ]
