# Generated by Django 5.2.1 on 2025-05-29 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_pdc_timbre_fiscal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdc',
            name='cd',
            field=models.ForeignKey(help_text='Order', on_delete=django.db.models.deletion.CASCADE, related_name='produit_commande', to='api.cd'),
        ),
    ]
