# Generated by Django 5.2.1 on 2025-05-29 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_merge_20250529_0211"),
        ("api", "0027_pdc_timbre_fiscal"),
    ]

    operations = []
