# Generated by Django 5.2.1 on 2025-05-29 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_pdc_cd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Bank name', max_length=255)),
                ('address', models.CharField(help_text='Bank address', max_length=255)),
                ('rib', models.CharField(help_text='Bank RIB', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='traite',
            name='acceptation',
            field=models.CharField(blank=True, help_text='Acceptation information', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='traite',
            name='aval',
            field=models.CharField(blank=True, help_text='Aval information', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='traite',
            name='bank',
            field=models.ForeignKey(blank=True, help_text='Bank associated with the traite', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traites', to='api.bank'),
        ),
    ]
