# Generated by Django 5.2.1 on 2025-05-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_alter_pdc_cd"),
        ("api", "0028_merge_0026_merge_20250529_0211_0027_pdc_timbre_fiscal"),
    ]

    operations = []
