# Generated by Django 5.2.1 on 2025-05-31 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_bank_traite_acceptation_traite_aval_traite_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traite',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='traite',
            name='acceptation',
        ),
        migrations.RemoveField(
            model_name='traite',
            name='aval',
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
