# Generated by Django 5.2.1 on 2025-06-04 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_merge_20250529_1101'),
        ('api', '0030_remove_traite_bank_remove_traite_acceptation_and_more'),
    ]

    operations = [
    ]
