# Generated by Django 5.2.1 on 2025-06-05 09: commentMore actions

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_merge_20250604_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='mode_paiement',
            field=models.CharField(choices=[('traite', 'Traite'), ('cash', 'Comptant'), ('mixte', 'Mixte'), ('virement', 'Virement')], default='cash', help_text='Payment method', max_length=20),
        ),
        migrations.AddField(
            model_name='commande',
            name='timbre_fiscal',
            field=models.FloatField(blank=True, help_text='Fiscal stamp', null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='numero_commande',
            field=models.CharField(blank=True, help_text='Order number', max_length=50, unique=True),
        ),
    ]