# Generated by Django 5.2.1 on 2025-06-05 09:

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_commande_mode_paiement_commande_timbre_fiscal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='numero_fiscal',
            field=models.CharField(help_text='Fiscal registration number', max_length=255, unique=True, validators=[api.models.validate_matricule_fiscal]),
        ),
    ]