# Generated by Django 5.2.1 on 2025-06-05 09:52
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_client_numero_fiscal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='epaisseur',
            field=models.FloatField(blank=True, help_text='Thickness of the product in mm', null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='largeur',
            field=models.FloatField(blank=True, help_text='Width of the product in mm', null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='longueur',
            field=models.FloatField(blank=True, help_text='Length of the product in mm', null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='surface',
            field=models.FloatField(blank=True, help_text='Surface area of the product in m²', null=True),
        ),
    ]