# Generated by Django 5.2.1 on 2025-06-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_plantraite_date_emission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traite',
            name='status',
            field=models.CharField(choices=[('non_paye', 'Non payée'), ('paye', 'Payée')], default='non_paye', help_text='Traite status', max_length=20),
        ),
    ]
