# Generated by Django 5.2.1 on 2025-06-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_bonretour_deleted_at_bonretour_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonretour',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date when the BON returned was deleted', null=True),
        ),
        migrations.AlterField(
            model_name='bonretour',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='BON returned deleted'),
        ),
        migrations.AlterField(
            model_name='client',
            name='code_client',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='matiereretour',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date when the material returned was deleted', null=True),
        ),
        migrations.AlterField(
            model_name='matiereretour',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Material returned deleted'),
        ),
        migrations.AlterField(
            model_name='produitcommande',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date when the product entry was deleted', null=True),
        ),
        migrations.AlterField(
            model_name='produitcommande',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Product entry deleted'),
        ),
        migrations.AlterField(
            model_name='produitdevis',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date when the product entry was deleted', null=True),
        ),
        migrations.AlterField(
            model_name='produitdevis',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Product entry deleted'),
        ),
    ]
