# Generated by Django 5.2.1 on 2025-06-03 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_traite_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantraite',
            name='client',
        ),
        migrations.RemoveField(
            model_name='plantraite',
            name='numero_facture',
        ),
        migrations.AlterField(
            model_name='plantraite',
            name='date_emission',
            field=models.DateField(auto_now_add=True, help_text='Invoice generation date'),
        ),
        migrations.AlterField(
            model_name='plantraite',
            name='date_premier_echeance',
            field=models.DateField(blank=True, help_text='Date of the first installment', null=True),
        ),
        migrations.AlterField(
            model_name='plantraite',
            name='facture',
            field=models.OneToOneField(help_text='Invoice', on_delete=django.db.models.deletion.CASCADE, to='api.facture'),
        ),
        migrations.AlterField(
            model_name='plantraite',
            name='matricule_fiscal',
            field=models.CharField(blank=True, help_text='Matricule fiscal', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plantraite',
            name='mode_paiement',
            field=models.CharField(choices=[('traite', 'Traite'), ('cash', 'Comptant'), ('mixte', 'Mixte'), ('virement', 'Virement')], default='traite', help_text='Payment method for the installment plan', max_length=20),
        ),
        migrations.AlterField(
            model_name='plantraite',
            name='montant_total',
            field=models.FloatField(blank=True, help_text='Total amount', null=True),
        ),
        migrations.AlterField(
            model_name='plantraite',
            name='nom_raison_sociale',
            field=models.CharField(blank=True, help_text='Nom de la raison sociale', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plantraite',
            name='nombre_traite',
            field=models.PositiveIntegerField(help_text='Number of traitements'),
        ),
        migrations.AlterField(
            model_name='plantraite',
            name='periode',
            field=models.PositiveIntegerField(blank=True, help_text='Period between each milking', null=True),
        ),
        migrations.AlterField(
            model_name='plantraite',
            name='status',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('PAYEE', 'payée')], default='EN_COURS', help_text='Traite status', max_length=20),
        ),
        migrations.AlterField(
            model_name='traite',
            name='status',
            field=models.CharField(choices=[('NON_PAYEE', 'Non payée'), ('PAYEE', 'Payée')], default='NON_PAYEE', help_text='Traite status', max_length=20),
        ),
    ]
