# Generated by Django 5.2.1 on 2025-06-03 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_plantraite_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantraite',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.client'),
        ),
        migrations.AddField(
            model_name='plantraite',
            name='numero_facture',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plantraite',
            name='date_emission',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='plantraite',
            name='date_premier_echeance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantraite',
            name='facture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.facturetravaux'),
        ),
        migrations.AlterField(
            model_name='plantraite',
            name='matricule_fiscal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plantraite',
            name='mode_paiement',
            field=models.CharField(choices=[('traite', 'Traite'), ('cash', 'Comptant'), ('mixte', 'Mixte'), ('virement', 'Virement')], default='traite', max_length=20),
        ),
        migrations.AlterField(
            model_name='plantraite',
            name='montant_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantraite',
            name='nom_raison_sociale',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plantraite',
            name='nombre_traite',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='plantraite',
            name='periode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantraite',
            name='status',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('PAYEE', 'Payée')], default='EN_COURS', max_length=20),
        ),
        migrations.AlterField(
            model_name='traite',
            name='date_echeance',
            field=models.DateField(help_text="Date d'échéance"),
        ),
        migrations.AlterField(
            model_name='traite',
            name='montant',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traite',
            name='plan_traite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traites', to='api.plantraite'),
        ),
        migrations.AlterField(
            model_name='traite',
            name='status',
            field=models.CharField(choices=[('NON_PAYEE', 'Non payée'), ('PAYEE', 'Payée')], default='NON_PAYEE', max_length=20),
        ),
    ]
