# Generated by Django 5.2.1 on 2025-06-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_bonretour_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traite',
            name='status',
            field=models.CharField(default='NON_PAYEE', max_length=255),
        ),
    ]
