# Generated by Django 5.2.1 on 2025-06-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_bonretour_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatierePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_matiere', models.CharField(choices=[('acier', 'Acier'), ('acier_inoxydable', 'Acier inoxydable'), ('aluminium', 'Aluminium'), ('laiton', 'Laiton'), ('cuivre', 'Cuivre'), ('acier_galvanise', 'Acier galvanisé'), ('autre', 'Autre')], default='autre', help_text='Material type', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Material description', null=True)),
                ('thickness', models.IntegerField(blank=True, help_text='Thickness of the material in mm', null=True)),
                ('length', models.IntegerField(blank=True, help_text='Length of the material in mm', null=True)),
                ('width', models.IntegerField(blank=True, help_text='Width of the material in mm', null=True)),
                ('surface', models.IntegerField(blank=True, help_text='Surface area of the material in m²', null=True)),
                ('prix_unitaire', models.FloatField(blank=True, help_text='Unit price of the material', null=True)),
                ('quantite', models.PositiveIntegerField(default=0, help_text='Quantity in stock')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date when the material was created')),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True, help_text='Date when the material was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Material deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date when the material was deleted', null=True)),
            ],
        ),
    ]
