# Generated by Django 5.2.1 on 2025-06-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_matierepurchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matierepurchase',
            name='length',
        ),
        migrations.RemoveField(
            model_name='matierepurchase',
            name='surface',
        ),
        migrations.RemoveField(
            model_name='matierepurchase',
            name='thickness',
        ),
        migrations.RemoveField(
            model_name='matierepurchase',
            name='width',
        ),
        migrations.AddField(
            model_name='matierepurchase',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='matierepurchase',
            name='type_matiere',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
