# Generated by Django 5.2.1 on 2025-06-10 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_remove_matierepurchase_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matierepurchase',
            name='type_matiere',
        ),
    ]
