# Generated by Django 5.2.1 on 2025-06-12 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_traite_status'),
        ('api', '0039_remove_matierepurchase_type_matiere'),
    ]

    operations = [
    ]
