# Generated by Django 5.2.1 on 2025-06-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_merge_20250612_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='matierepurchase',
            name='purshase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='code_produit',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
