# Generated by Django 5.2.1 on 2025-06-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_matierepurchase_purshase_date_produit_code_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveaux',
            name='remise',
            field=models.FloatField(default=0, help_text='Remise appliquée sur le travail (en DT)'),
        ),
    ]
