# Generated by Django 5.2.1 on 2025-06-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_traveaux_remise'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='code_client',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='commandeproduit',
            name='code_produit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
