# Generated by Django 5.2.1 on 2025-06-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_commande_code_client_commandeproduit_code_produit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandeproduit',
            name='code_produit',
        ),
    ]
