# Generated by Django 5.2.1 on 2025-06-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_remove_commandeproduit_code_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd',
            name='mode_paiement',
            field=models.CharField(choices=[('traite', 'Traite'), ('cash', 'Comptant'), ('cheque', 'Cheque'), ('virement', 'Virement'), ('carte', 'Carte')], default='cash', help_text='Payment method', max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='mode_paiement',
            field=models.CharField(choices=[('traite', 'Traite'), ('cash', 'Comptant'), ('cheque', 'Cheque'), ('virement', 'Virement'), ('carte', 'Carte')], default='cash', help_text='Payment method', max_length=20),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='derniere_mise_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='length',
            field=models.IntegerField(blank=True, help_text='Length in mm', null=True),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='prix_unitaire',
            field=models.FloatField(blank=True, help_text='Unit price', null=True),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='remaining_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Remaining quantity'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='surface',
            field=models.IntegerField(blank=True, help_text='Surface area (m²)', null=True),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='thickness',
            field=models.IntegerField(blank=True, help_text='Thickness in mm', null=True),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='width',
            field=models.IntegerField(blank=True, help_text='Width in mm', null=True),
        ),
    ]
