<<<<<<< HEAD
# Generated by Django 5.2.1 on 2025-06-17 16:48
=======
# Generated by Django 5.2.1 on 2025-06-18 17:47
>>>>>>> 5c7cdbc96fc66ddee2da9a697f13c50a3ae794bc

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_matiere_date_creation_alter_matiere_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd',
            name='mode_paiement',
            field=models.CharField(choices=[('traite', 'Traite'), ('cash', 'Comptant'), ('cheque', 'Cheque'), ('virement', 'Virement'), ('carte', 'Carte')], default='cash', help_text='Payment method', max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='mode_paiement',
            field=models.CharField(choices=[('traite', 'Traite'), ('cash', 'Comptant'), ('cheque', 'Cheque'), ('virement', 'Virement'), ('carte', 'Carte')], default='cash', help_text='Payment method', max_length=20),
        ),
    ]
