# Generated by Django 5.2.1 on 2025-06-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_cd_mode_paiement_alter_commande_mode_paiement'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matiereretour',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='bonretour',
            name='matieres',
        ),
        migrations.AddField(
            model_name='matiereretour',
            name='nom_matiere',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='matiereretour',
            name='matiere',
        ),
    ]
