# Generated by Django 5.2.1 on 2025-06-19 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_matiereretour_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiereretour',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retours', to='api.matiere'),
        ),
    ]
