# Generated by Django 5.2.1 on 2025-06-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_matiereretour_matiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traite',
            name='status',
            field=models.CharField(choices=[('NON_PAYEE', 'Non payée'), ('PAYEE', 'Payée')], default='NON_PAYEE', max_length=255),
        ),
    ]
