# Generated by Django 5.2.1 on 2025-06-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_plantraite_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantraite',
            name='status',
            field=models.CharField(choices=[('NON_PAYEE', 'Non payée'), ('PAYEE', 'Payée')], default='NON_PAYEE', max_length=20),
        ),
    ]
