# Generated by Django 5.2.1 on 2025-06-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_plantraite_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantraite',
            name='acceptance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantraite',
            name='bank_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantraite',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plantraite',
            name='notice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantraite',
            name='rip',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
