# Generated by Django 5.2.1 on 2025-06-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_plantraite_acceptance_plantraite_bank_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='timbre_fiscal',
            field=models.DecimalField(decimal_places=2, default=0.6, max_digits=10, verbose_name='Timbre fiscal'),
        ),
    ]
