# Generated by Django 5.2.1 on 2025-06-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_devis_timbre_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantraite',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='devis',
            name='timbre_fiscal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Timbre fiscal'),
        ),
    ]
