# Generated by Django 5.2.1 on 2025-06-24 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_plantraite_is_deleted_alter_devis_timbre_fiscal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matierepurchase',
            name='purshase_date',
        ),
    ]
