# Generated by Django 5.2.1 on 2025-06-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_remove_matierepurchase_purshase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='matierepurchase',
            name='purshase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
