# Generated by Django 5.2.1 on 2025-06-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_matierepurchase_purshase_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatierePremiereAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=100, unique=True)),
                ('nom_matiere', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('metaux', 'Métaux'), ('fixation', 'Fixation'), ('plastique', 'Plastique'), ('autre', 'Autre')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('unite_mesure', models.CharField(choices=[('kg', 'Kilogramme'), ('pcs', 'Pièce'), ('m2', 'Mètre carré'), ('m3', 'Mètre cube')], max_length=10)),
                ('remaining_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_minimum', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('emplacement', models.CharField(blank=True, max_length=200, null=True)),
                ('fournisseur_principal', models.CharField(max_length=200)),
                ('prix_unitaire', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date_reception', models.DateField()),
                ('ref_fournisseur', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
