# Generated by Django 5.2.1 on 2025-06-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_matierepremiereachat'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='type_facture',
            field=models.CharField(default='', help_text='Product or Bon invoice'),
        ),
    ]
