# Generated by Django 5.2.1 on 2025-06-26 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_alter_matierepremiereachat_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matierepremiereachat',
            name='unite_mesure',
        ),
    ]
