# Generated by Django 5.2.1 on 2025-06-26 09:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_remove_matierepremiereachat_unite_mesure'),
    ]

    operations = [
        migrations.AddField(
            model_name='matierepremiereachat',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
