# Generated by Django 5.2.1 on 2025-06-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_remove_cd_facture_commande_bons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='bons',
        ),
        migrations.AddField(
            model_name='cd',
            name='bons',
            field=models.ManyToManyField(blank=True, help_text='Liste des bons liés à cette commande', related_name='commandes_associees', to='api.facturetravaux'),
        ),
    ]
