# Generated by Django 5.2.1 on 2025-06-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_alter_matierepremiereachat_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='matierepremiereachat',
            name='epaisseur',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Épaisseur en mm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='matierepremiereachat',
            name='largeur',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Largeur en mètres', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='matierepremiereachat',
            name='longueur',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Longueur en mètres', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='matierepremiereachat',
            name='surface',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Surface en m²', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='matierepremiereachat',
            name='unite_mesure',
            field=models.CharField(choices=[('kg', 'Kilogramme'), ('pcs', 'Pièce'), ('m2', 'Mètre carré'), ('m3', 'Mètre cube')], default='kg', max_length=10),
        ),
    ]
