# Generated by Django 5.2.1 on 2025-06-27 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_remove_commande_bons_cd_bons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='facture',
        ),
        migrations.AddField(
            model_name='cd',
            name='facture',
            field=models.OneToOneField(blank=True, help_text='Associated invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande_associee', to='api.facturetravaux'),
        ),
    ]
