# Generated by Django 5.2.1 on 2025-06-26 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_remove_pdc_type_facture_cd_type_facture'),
        ('api', '0062_matierepremiereachat_epaisseur_and_more'),
    ]

    operations = [
    ]
