# Generated by Django 5.2.1 on 2025-06-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_remove_commande_facture_cd_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturetravaux',
            name='timbre_fiscal',
            field=models.IntegerField(default=1, help_text='Timbre fiscal'),
        ),
        migrations.AddField(
            model_name='traveaux',
            name='remise_percent_produit',
            field=models.FloatField(default=0, help_text='Remise appliquée sur le travail (en DT)'),
        ),
        migrations.AddField(
            model_name='traveaux',
            name='remise_produit',
            field=models.FloatField(default=0, help_text='Remise appliquée sur le travail (en DT)'),
        ),
    ]
