# Generated by Django 5.2.1 on 2025-06-29 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_merge_20250626_2320'),
        ('api', '0063_remove_commande_facture_cd_facture'),
    ]

    operations = [
    ]
