# Generated by Django 5.2.1 on 2025-06-30 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_facturetravaux_timbre_fiscal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturetravaux',
            name='timbre_fiscal',
        ),
        migrations.RemoveField(
            model_name='traveaux',
            name='remise_percent_produit',
        ),
        migrations.RemoveField(
            model_name='traveaux',
            name='remise_produit',
        ),
    ]
