# Generated by Django 5.2.1 on 2025-06-30 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_remove_facturetravaux_timbre_fiscal_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='produitcommande',
            unique_together=set(),
        ),
    ]
