# Generated by Django 5.2.1 on 2025-06-30 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_alter_produitcommande_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pdc',
            unique_together=set(),
        ),
    ]
