# Generated by Django 5.2.1 on 2025-06-30 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_alter_pdc_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdc',
            name='bon_source',
            field=models.ForeignKey(blank=True, help_text='Bon from which this product was included', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits_inclus', to='api.facturetravaux'),
        ),
    ]
