# Generated by Django 5.2.1 on 2025-06-30 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_pdc_bon_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdc',
            name='bon_source',
        ),
    ]
