# Generated by Django 5.2.1 on 2025-06-30 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_remove_pdc_bon_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdc',
            name='bon_numero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pdc',
            name='bon_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits_utilises', to='api.facturetravaux'),
        ),
    ]
