# Generated by Django 5.2.1 on 2025-06-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_pdc_bon_numero_pdc_bon_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturetravaux',
            name='timbre_fiscal',
            field=models.IntegerField(default=1, help_text='Timbre fiscal'),
        ),
        migrations.AddField(
            model_name='traveaux',
            name='remise_percent_produit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage discount on this product', max_digits=5),
        ),
        migrations.AddField(
            model_name='traveaux',
            name='remise_produit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount value applied on this product', max_digits=10),
        ),
    ]
