# Generated by Django 5.2.1 on 2025-06-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_facturetravaux_timbre_fiscal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturetravaux',
            name='timbre_fiscal',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
