# Generated by Django 5.2.1 on 2025-06-30 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_merge_20250629_1658'),
        ('api', '0072_alter_facturetravaux_timbre_fiscal'),
    ]

    operations = [
    ]
