# Generated by Django 5.2.1 on 2025-07-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_alter_facturetravaux_timbre_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturetravaux',
            name='nature',
            field=models.CharField(choices=[('facture', 'Facture'), ('avoir-facture', 'Avoir-facture'), ('avoir', 'Avoir')], default='facture', max_length=10),
        ),
    ]
