# Generated by Django 5.2.1 on 2025-07-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_facturetravaux_nature'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd',
            name='nature',
            field=models.CharField(choices=[('facture', 'Facture'), ('avoir', 'Avoir')], default='facture', max_length=10),
        ),
    ]
