# Generated by Django 5.2.1 on 2025-07-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_merge_20250630_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactureAchatMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=100, null=True)),
                ('fournisseur', models.CharField(blank=True, max_length=255, null=True)),
                ('type_achat', models.CharField(blank=True, choices=[('matière première', 'matière première'), ('consommable', 'consommable'), ('autres', 'autres')], max_length=50, null=True)),
                ('prix_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_facture', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
