# Generated by Django 5.2.1 on 2025-07-01 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_bonlivraison_bonlivraisonligne'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonLivraisonAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100, unique=True)),
                ('fournisseur', models.CharField(max_length=255)),
                ('type_achat', models.CharField(choices=[('matière première', 'matière première'), ('consommable', 'consommable'), ('autres', 'autres')], max_length=100)),
                ('date_livraison', models.DateField(default=django.utils.timezone.now)),
                ('prix_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('livraisons', models.JSONField(default=list)),
            ],
        ),
        migrations.RemoveField(
            model_name='bonlivraisonligne',
            name='bon_livraison',
        ),
        migrations.DeleteModel(
            name='BonLivraison',
        ),
        migrations.DeleteModel(
            name='BonLivraisonLigne',
        ),
    ]
