# Generated by Django 5.2.1 on 2025-07-01 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_bonlivraisonachat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonLivraisonMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=100, null=True)),
                ('fournisseur', models.CharField(blank=True, max_length=255, null=True)),
                ('type_achat', models.CharField(blank=True, choices=[('matière première', 'matière première'), ('consommable', 'consommable'), ('autres', 'autres')], max_length=50, null=True)),
                ('prix_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_livraison', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.PositiveIntegerField()),
                ('bon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='api.bonlivraisonmatiere')),
            ],
        ),
        migrations.DeleteModel(
            name='BonLivraisonAchat',
        ),
    ]
