# Generated by Django 5.2.1 on 2025-07-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_bonlivraisonmatiere_livraison_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('num_reg_fiscal', models.CharField(max_length=100, unique=True)),
                ('adresse', models.CharField(max_length=500)),
                ('telephone', models.CharField(max_length=20)),
                ('infos_complementaires', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
