# Generated by Django 5.2.1 on 2025-07-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_consommable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matierepremiereachat',
            name='categorie',
            field=models.CharField(choices=[('acier', 'Acier'), ('acier_inoxydable', 'Acier inoxydable'), ('aluminium', 'Aluminium'), ('laiton', 'Laiton'), ('cuivre', 'Cuivre'), ('acier_galvanise', 'Acier galvanisé'), ('metaux', 'Metaux'), ('autre', 'Autre')], default='autre', max_length=100),
        ),
    ]
