# Generated by Django 5.2.1 on 2025-07-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_alter_matierepremiereachat_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='remarques',
            field=models.TextField(blank=True, help_text='Remarques standard sur la commande', null=True),
        ),
    ]
