# Generated by Django 5.2.1 on 2025-07-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_commande_remarques'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matiereretour',
            options={'verbose_name': 'Matière retournée', 'verbose_name_plural': 'Matières retournées'},
        ),
    ]
