# Generated by Django 5.2.1 on 2025-07-04 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_alter_matiereretour_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matiereretour',
            options={},
        ),
    ]
