# Generated by Django 5.2.1 on 2025-07-07 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_cd_nature'),
        ('api', '0084_alter_matiereretour_options'),
    ]

    operations = [
    ]
