# Generated by Django 5.2.1 on 2025-07-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_merge_0074_cd_nature_0084_alter_matiereretour_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonretour',
            name='numero_bon',
            field=models.CharField(blank=True, help_text='Bon number', max_length=50, unique=True),
        ),
    ]
