# Generated by Django 5.2.1 on 2025-07-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_merge_0074_cd_nature_0084_alter_matiereretour_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiereusage',
            name='source',
            field=models.CharField(help_text='Material usage source, stock or client', null=True),
        ),
    ]
