# Generated by Django 5.2.1 on 2025-07-07 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_alter_bonretour_numero_bon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiereretour',
            name='bon_retour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matiere_retours', to='api.bonretour', verbose_name='Bon de retour'),
        ),
        migrations.AlterField(
            model_name='matiereretour',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date de suppression logique', null=True, verbose_name='Date suppression'),
        ),
        migrations.AlterField(
            model_name='matiereretour',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Indique si le retour a été supprimé logiquement', verbose_name='Supprimé'),
        ),
        migrations.AlterField(
            model_name='matiereretour',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retours', to='api.matiere', verbose_name='Matière'),
        ),
        migrations.AlterField(
            model_name='matiereretour',
            name='nom_matiere',
            field=models.CharField(blank=True, help_text='Nom de la matière (optionnel, utilisé si la matière liée est absente)', max_length=255, null=True, verbose_name='Nom matière (si matière supprimée ou non référencée)'),
        ),
        migrations.AlterField(
            model_name='matiereretour',
            name='quantite_retournee',
            field=models.PositiveIntegerField(default=1, help_text='Quantité de matière retournée', verbose_name='Quantité retournée'),
        ),
    ]
