# Generated by Django 5.2.1 on 2025-07-08 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_matiereusage_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiereusage',
            name='achat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.matierepremiereachat'),
        ),
        migrations.AlterField(
            model_name='matiereusage',
            name='source',
            field=models.CharField(choices=[('stock', 'Main Stock'), ('client', 'Client Provided')], help_text='Material usage source, stock or client', null=True),
        ),
    ]
