# Generated by Django 5.2.1 on 2025-07-08 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_matiereusage_achat_alter_matiereusage_source'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matiereusage',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='matiereusage',
            name='matiere',
            field=models.ForeignKey(blank=True, help_text='Material', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='api.matiere'),
        ),
    ]
