# Generated by Django 5.2.1 on 2025-07-08 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_alter_matiereretour_bon_retour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factureachatmatiere',
            name='mode_paiement',
            field=models.CharField(choices=[('traite', 'Traite'), ('cash', 'Comptant'), ('cheque', 'Cheque'), ('virement', 'Virement'), ('carte', 'Carte')], default='cash', help_text='Payment method', max_length=20),
        ),
        migrations.AlterField(
            model_name='bonretour',
            name='numero_bon',
            field=models.CharField(help_text='Bon number', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='matiereretour',
            name='bon_retour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matiere_retours', to='api.bonretour'),
        ),
        migrations.AlterField(
            model_name='matiereretour',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date when the material returned was deleted', null=True),
        ),
        migrations.AlterField(
            model_name='matiereretour',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Material returned deleted'),
        ),
        migrations.AlterField(
            model_name='matiereretour',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retours', to='api.matiere'),
        ),
        migrations.AlterField(
            model_name='matiereretour',
            name='nom_matiere',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='matiereretour',
            name='quantite_retournee',
            field=models.PositiveIntegerField(default=1, help_text='Quantity of material returned'),
        ),
    ]
