# Generated by Django 5.2.1 on 2025-07-08 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_factureachatmatiere_mode_paiement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonRetourFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bon', models.CharField(help_text='Numéro du bon', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée'), ('completed', 'Complété'), ('cancelled', 'Annulée')], default='draft', help_text='Statut du bon de retour', max_length=20)),
                ('date_reception', models.DateField(help_text='Date de réception')),
                ('date_retour', models.DateField(help_text='Date de retour')),
                ('date_emission', models.DateField(auto_now_add=True, help_text='Date d’émission')),
                ('notes', models.TextField(blank=True, help_text='Remarques supplémentaires', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Bon supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date suppression', null=True)),
                ('fournisseur', models.ForeignKey(help_text='Fournisseur concerné', on_delete=django.db.models.deletion.CASCADE, related_name='bons_retour_fournisseur', to='api.fournisseur')),
            ],
            options={
                'verbose_name': 'Bon de Retour Fournisseur',
                'verbose_name_plural': 'Bons de Retour Fournisseur',
                'ordering': ['-date_retour', '-numero_bon'],
            },
        ),
        migrations.CreateModel(
            name='MatiereRetourFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_matiere', models.CharField(blank=True, max_length=255, null=True)),
                ('quantite_retournee', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('bon_retour', models.ForeignKey(help_text='Bon de retour associé', on_delete=django.db.models.deletion.CASCADE, related_name='matiere_retours', to='api.bonretourfournisseur')),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retours_fournisseur', to='api.matiere')),
            ],
            options={
                'verbose_name': 'Matière retournée fournisseur',
                'verbose_name_plural': 'Matières retournées fournisseur',
            },
        ),
        migrations.AddIndex(
            model_name='bonretourfournisseur',
            index=models.Index(fields=['numero_bon'], name='api_bonreto_numero__9c4037_idx'),
        ),
        migrations.AddIndex(
            model_name='bonretourfournisseur',
            index=models.Index(fields=['fournisseur'], name='api_bonreto_fournis_c931a6_idx'),
        ),
        migrations.AddIndex(
            model_name='bonretourfournisseur',
            index=models.Index(fields=['date_retour'], name='api_bonreto_date_re_87fc9c_idx'),
        ),
        migrations.AddIndex(
            model_name='bonretourfournisseur',
            index=models.Index(fields=['status'], name='api_bonreto_status_572801_idx'),
        ),
    ]
