# Generated by Django 5.2.1 on 2025-07-08 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_bonretourfournisseur_matiereretourfournisseur_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonretourfournisseur',
            options={},
        ),
        migrations.AlterModelOptions(
            name='matiereretourfournisseur',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='bonretourfournisseur',
            name='api_bonreto_numero__9c4037_idx',
        ),
        migrations.RemoveIndex(
            model_name='bonretourfournisseur',
            name='api_bonreto_fournis_c931a6_idx',
        ),
        migrations.RemoveIndex(
            model_name='bonretourfournisseur',
            name='api_bonreto_date_re_87fc9c_idx',
        ),
        migrations.RemoveIndex(
            model_name='bonretourfournisseur',
            name='api_bonreto_status_572801_idx',
        ),
        migrations.AlterField(
            model_name='bonretourfournisseur',
            name='date_emission',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bonretourfournisseur',
            name='date_reception',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bonretourfournisseur',
            name='date_retour',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bonretourfournisseur',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bonretourfournisseur',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_retour_fournisseur', to='api.fournisseur'),
        ),
        migrations.AlterField(
            model_name='bonretourfournisseur',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bonretourfournisseur',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bonretourfournisseur',
            name='numero_bon',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='bonretourfournisseur',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée'), ('completed', 'Complété'), ('cancelled', 'Annulée')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='matiereretourfournisseur',
            name='bon_retour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matiere_retours', to='api.bonretourfournisseur'),
        ),
    ]
