# Generated by Django 5.2.1 on 2025-07-08 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_alter_bonretourfournisseur_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTraiteFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_traite', models.PositiveIntegerField()),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NON_PAYEE', 'Non payée'), ('PAYEE', 'Payée')], default='NON_PAYEE', max_length=20)),
                ('date_premier_echeance', models.DateField(blank=True, null=True)),
                ('periode', models.PositiveIntegerField(blank=True, null=True)),
                ('montant_total', models.FloatField(blank=True, null=True)),
                ('nom_raison_sociale', models.CharField(blank=True, max_length=255, null=True)),
                ('matricule_fiscal', models.CharField(blank=True, max_length=255, null=True)),
                ('mode_paiement', models.CharField(choices=[('traite', 'Traite'), ('cash', 'Comptant'), ('mixte', 'Mixte'), ('virement', 'Virement')], default='traite', max_length=20)),
                ('rip', models.CharField(blank=True, max_length=40, null=True)),
                ('acceptance', models.TextField(blank=True, null=True)),
                ('notice', models.TextField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_address', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('facture', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.factureachatmatiere')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.fournisseur')),
            ],
            options={
                'ordering': ['-date_emission', 'date_premier_echeance'],
            },
        ),
        migrations.CreateModel(
            name='TraiteFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_echeance', models.DateField(help_text="Date d'échéance")),
                ('status', models.CharField(choices=[('NON_PAYEE', 'Non payée'), ('PAYEE', 'Payée')], default='NON_PAYEE', max_length=255)),
                ('montant', models.FloatField(blank=True, null=True)),
                ('plan_traite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traites', to='api.plantraitefournisseur')),
            ],
            options={
                'ordering': ['-date_echeance'],
            },
        ),
        migrations.AddIndex(
            model_name='plantraitefournisseur',
            index=models.Index(fields=['facture'], name='api_plantra_facture_fefd98_idx'),
        ),
        migrations.AddIndex(
            model_name='plantraitefournisseur',
            index=models.Index(fields=['date_emission'], name='api_plantra_date_em_fd8c52_idx'),
        ),
        migrations.AddIndex(
            model_name='plantraitefournisseur',
            index=models.Index(fields=['date_premier_echeance'], name='api_plantra_date_pr_7a471c_idx'),
        ),
        migrations.AddIndex(
            model_name='plantraitefournisseur',
            index=models.Index(fields=['status'], name='api_plantra_status_34e25a_idx'),
        ),
        migrations.AddIndex(
            model_name='traitefournisseur',
            index=models.Index(fields=['plan_traite'], name='api_traitef_plan_tr_e35298_idx'),
        ),
        migrations.AddIndex(
            model_name='traitefournisseur',
            index=models.Index(fields=['date_echeance'], name='api_traitef_date_ec_7ef8c4_idx'),
        ),
        migrations.AddIndex(
            model_name='traitefournisseur',
            index=models.Index(fields=['status'], name='api_traitef_status_1ec3dd_idx'),
        ),
    ]
