# Generated by Django 5.2.1 on 2025-07-11 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_alter_matiereusage_unique_together_and_more'),
        ('api', '0091_plantraitefournisseur_traitefournisseur_and_more'),
    ]

    operations = [
    ]
