# Generated by Django 5.2.1 on 2025-07-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_merge_20250711_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantraitefournisseur',
            name='status',
            field=models.CharField(choices=[('NON_PAYEE', 'Non payée'), ('PAYEE', 'Payée'), ('PARTIELLEMENT_PAYEE', 'Partiellement payée')], default='NON_PAYEE', max_length=20),
        ),
        migrations.AlterField(
            model_name='traitefournisseur',
            name='status',
            field=models.CharField(choices=[('NON_PAYEE', 'Non payée'), ('PAYEE', 'Payée'), ('PARTIELLEMENT_PAYEE', 'Partiellement payée')], default='NON_PAYEE', max_length=255),
        ),
    ]
