# Generated by Django 5.2.1 on 2025-07-11 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_employe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('date_demande', models.DateField()),
                ('motif', models.TextField()),
                ('nbr_mensualite', models.PositiveIntegerField()),
                ('mensualite', models.FloatField()),
                ('progression', models.FloatField(default=0)),
                ('reste', models.FloatField()),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Acceptée', 'Acceptée'), ('Refusée', 'Refusée')], default='En attente', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='api.employe')),
            ],
        ),
    ]
