# Generated by Django 5.2.1 on 2025-07-11 20:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_avance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avance',
            old_name='employee',
            new_name='employe',
        ),
        migrations.AddField(
            model_name='avance',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avance',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
