# Generated by Django 5.2.1 on 2025-07-11 21:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_rename_employee_avance_employe_avance_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avance',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='avance',
            old_name='date_creation',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='avance',
            old_name='date_modification',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='avance',
            name='mensualite',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='avance',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='avance',
            name='nbr_mensualite',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='avance',
            name='progression',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='avance',
            name='reste',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='RemboursementAvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_remboursement', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('avance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='api.avance')),
            ],
            options={
                'ordering': ['-date_remboursement'],
            },
        ),
    ]
