# Generated by Django 5.2.1 on 2025-07-11 21:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_alter_avance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avance',
            options={},
        ),
        migrations.RenameField(
            model_name='avance',
            old_name='employe',
            new_name='employee',
        ),
        migrations.RemoveField(
            model_name='avance',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='avance',
            name='mensualite',
        ),
        migrations.RemoveField(
            model_name='avance',
            name='progression',
        ),
        migrations.RemoveField(
            model_name='avance',
            name='reste',
        ),
        migrations.RemoveField(
            model_name='avance',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='avance',
            name='date_demande',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='avance',
            name='montant',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='avance',
            name='nbr_mensualite',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('montant', models.FloatField()),
                ('avance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='api.avance')),
            ],
        ),
        migrations.DeleteModel(
            name='RemboursementAvance',
        ),
    ]
