# Generated by Django 5.2.1 on 2025-07-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_alter_avance_options_rename_employe_avance_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='categorie',
            field=models.CharField(blank=True, choices=[('cadre', 'Cadre'), ('non_cadre', 'Non Cadre')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='enfants_a_charge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employe',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='nombre_enfants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='numero_cnss',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='situation_familiale',
            field=models.CharField(blank=True, choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf(ve)')], max_length=20, null=True),
        ),
    ]
