# Generated by Django 5.2.1 on 2025-07-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_employe_categorie_employe_enfants_a_charge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='matricule',
        ),
        migrations.AlterField(
            model_name='employe',
            name='categorie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='code_contrat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='enfants_a_charge',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='id_employe',
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employe',
            name='nombre_enfants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='salaire',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='situation_familiale',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
