# Generated by Django 5.2.1 on 2025-07-12 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_remove_employe_matricule_alter_employe_categorie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('salaire_base', models.FloatField()),
                ('prime_anciennete', models.FloatField(default=0)),
                ('indemnite_presence', models.FloatField(default=0)),
                ('indemnite_transport', models.FloatField(default=0)),
                ('prime_langue', models.FloatField(default=0)),
                ('jours_feries_payes', models.FloatField(default=0)),
                ('absences_non_remunerees', models.FloatField(default=0)),
                ('prime_ramadan', models.FloatField(default=0)),
                ('prime_teletravail', models.FloatField(default=0)),
                ('avantage_assurance', models.FloatField(default=0)),
                ('conge_precedent', models.FloatField(default=0)),
                ('conge_acquis', models.FloatField(default=0)),
                ('conge_pris', models.FloatField(default=0)),
                ('conge_restant', models.FloatField(default=0)),
                ('conge_speciaux', models.FloatField(default=0)),
                ('conge_maladie_m', models.FloatField(default=0)),
                ('conge_maladie_a', models.FloatField(default=0)),
                ('banque', models.CharField(blank=True, max_length=100, null=True)),
                ('rib', models.CharField(blank=True, max_length=100, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='Générée', max_length=50)),
                ('salaire_brut', models.FloatField(default=0)),
                ('salaire_imposable', models.FloatField(default=0)),
                ('cnss_salarie', models.FloatField(default=0)),
                ('irpp', models.FloatField(default=0)),
                ('css', models.FloatField(default=0)),
                ('deduction_totale', models.FloatField(default=0)),
                ('cnss_patronal', models.FloatField(default=0)),
                ('accident_travail', models.FloatField(default=0)),
                ('charges_patronales', models.FloatField(default=0)),
                ('net_a_payer', models.FloatField(default=0)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_paie', to='api.employe')),
            ],
        ),
    ]
