# Generated by Django 5.2.1 on 2025-07-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_fichepaie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='enfants_a_charge',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
