# Generated by Django 5.2.1 on 2025-07-15 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_merge_20250712_0106'),
        ('api', '0102_alter_employe_enfants_a_charge'),
    ]

    operations = [
    ]
