# Generated by Django 5.2.1 on 2025-07-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_merge_20250715_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichepaie',
            name='avance_deduite',
            field=models.FloatField(default=0),
        ),
    ]
