# Generated by Django 5.2.1 on 2025-07-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_merge_20250715_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantraite',
            options={'ordering': ['-date_emission']},
        ),
    ]
