# Generated by Django 5.2.1 on 2025-07-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_alter_plantraite_options'),
        ('api', '0104_fichepaie_avance_deduite'),
    ]

    operations = [
    ]
