# Generated by Django 5.2.1 on 2025-07-18 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_alter_plantraite_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdc',
            old_name='bon_source',
            new_name='bon_id',
        ),
    ]
