# Generated by Django 5.2.1 on 2025-07-18 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_rename_bon_source_pdc_bon_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdc',
            old_name='bon_id',
            new_name='bonId',
        ),
    ]
