# Generated by Django 5.2.1 on 2025-07-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_merge_20250718_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
