# Generated by Django 5.2.1 on 2025-07-18 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_rename_bon_id_pdc_bonid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdc',
            old_name='bonId',
            new_name='bon_id',
        ),
    ]
