# Generated by Django 5.2.1 on 2025-07-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_cd_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
