# Generated by Django 5.2.1 on 2025-07-19 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_fichepaie_avance_deduite'),
        ('api', '0107_rename_bonid_pdc_bon_id'),
    ]

    operations = [
    ]
