# Generated by Django 5.2.1 on 2025-07-19 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_cd_deleted_at'),
        ('api', '0108_merge_20250719_1444'),
    ]

    operations = [
    ]
