# Generated by Django 5.2.1 on 2025-07-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_merge_0107_cd_deleted_at_0108_merge_20250719_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd',
            name='nature',
            field=models.CharField(choices=[('facture', 'Facture'), ('avoir-facture', 'Avoir-facture'), ('avoir', 'Avoir')], default='facture', max_length=20),
        ),
        migrations.AlterField(
            model_name='facturetravaux',
            name='nature',
            field=models.CharField(choices=[('facture', 'Facture'), ('avoir-facture', 'Avoir-facture'), ('avoir', 'Avoir')], default='facture', max_length=20),
        ),
    ]
