# Generated by Django 5.2.1 on 2025-07-22 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_merge_0107_cd_deleted_at_0107_rename_bonid_pdc_bon_id'),
        ('api', '0110_alter_cd_nature_alter_facturetravaux_nature'),
    ]

    operations = [
    ]
