# Generated by Django 5.2.1 on 2025-07-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_merge_20250722_0953'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['is_deleted'], name='api_produit_is_dele_c7754b_idx'),
        ),
    ]
