# Generated by Django 5.2.1 on 2025-07-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_produit_api_produit_is_dele_c7754b_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='produit',
            name='api_produit_is_dele_c7754b_idx',
        ),
    ]
