# Generated by Django 5.2.1 on 2025-07-23 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_remove_produit_api_produit_is_dele_c7754b_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=100, null=True)),
                ('fournisseur', models.CharField(blank=True, max_length=255, null=True)),
                ('type_achat', models.CharField(blank=True, choices=[('matière première', 'matière première'), ('consommable', 'consommable'), ('autres', 'autres')], max_length=50, null=True)),
                ('mode_paiement', models.CharField(choices=[('traite', 'Traite'), ('cash', 'Comptant'), ('cheque', 'Cheque'), ('virement', 'Virement'), ('carte', 'Carte')], default='cash', help_text='Payment method', max_length=20)),
                ('prix_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_facture', models.DateField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='achat',
            name='avoir',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='achats', to='api.avoir'),
            preserve_default=False,
        ),
    ]
