# Generated by Django 5.2.1 on 2025-07-23 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_avoir_achat_avoir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achat',
            name='avoir',
        ),
        migrations.DeleteModel(
            name='Avoir',
        ),
    ]
