# Generated by Django 5.2.1 on 2025-07-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_avoir_avoirarticle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avoir',
            options={},
        ),
        migrations.AddField(
            model_name='avoir',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
