# Generated by Django 5.2.1 on 2025-07-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_alter_avoir_options_avoir_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd',
            name='mixte_comptant',
            field=models.IntegerField(default=0, help_text='Cash part for mode_paiement mixte'),
        ),
        migrations.AddField(
            model_name='factureachatmatiere',
            name='mixte_comptant',
            field=models.IntegerField(default=0, help_text='Cash part for mode_paiement mixte'),
        ),
        migrations.AlterField(
            model_name='cd',
            name='mode_paiement',
            field=models.CharField(choices=[('traite', 'Traite'), ('cash', 'Comptant'), ('cheque', 'Cheque'), ('virement', 'Virement'), ('carte', 'Carte'), ('mixte', 'Mixte')], default='cash', help_text='Payment method', max_length=20),
        ),
        migrations.AlterField(
            model_name='factureachatmatiere',
            name='mode_paiement',
            field=models.CharField(choices=[('traite', 'Traite'), ('cash', 'Comptant'), ('cheque', 'Cheque'), ('virement', 'Virement'), ('carte', 'Carte'), ('mixte', 'Mixte')], default='cash', help_text='Payment method', max_length=20),
        ),
    ]
