# Generated by Django 5.2.1 on 2025-07-23 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_alter_avoir_options_avoir_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avoirarticle',
            name='avoir',
        ),
        migrations.DeleteModel(
            name='Avoir',
        ),
        migrations.DeleteModel(
            name='AvoirArticle',
        ),
    ]
