# Generated by Django 5.2.1 on 2025-07-23 19:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_remove_avoirarticle_avoir_delete_avoir_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fournisseur', models.CharField(blank=True, max_length=255, null=True)),
                ('type_avoir', models.CharField(blank=True, choices=[('retour marchandise', 'Retour marchandise'), ('remise commerciale', 'Remise commerciale'), ('erreur facturation', 'Erreur facturation'), ('autres', 'Autres')], max_length=50, null=True)),
                ('mode_paiement', models.CharField(choices=[('cash', 'Comptant'), ('cheque', 'Chèque'), ('virement', 'Virement Bancaire'), ('carte', 'Carte de crédit'), ('traite', 'Traite')], default='cash', max_length=20)),
                ('montant_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('date_avoir', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvoirArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quantite', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('avoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='api.avoir')),
            ],
            options={
                'verbose_name': "Article d'avoir",
                'verbose_name_plural': "Articles d'avoir",
            },
        ),
    ]
