# Generated by Django 5.2.1 on 2025-07-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_avoir_avoirarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
