# Generated by Django 5.2.1 on 2025-07-28 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_cd_mixte_comptant_factureachatmatiere_mixte_comptant_and_more'),
        ('api', '0120_fournisseur_deleted_at_fournisseur_is_deleted'),
    ]

    operations = [
    ]
