# Generated by Django 5.2.1 on 2025-07-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_merge_20250728_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd',
            name='statut',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='pending', help_text='Order status', max_length=20),
        ),
    ]
