# Generated by Django 5.2.1 on 2025-07-29 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_alter_cd_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonlivraisonmatiere',
            name='type_achat',
        ),
        migrations.RemoveField(
            model_name='factureachatmatiere',
            name='type_achat',
        ),
    ]
