# Generated by Django 5.2.1 on 2025-07-29 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_remove_bonlivraisonmatiere_type_achat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichepaie',
            old_name='date_creation',
            new_name='date_paiement',
        ),
    ]
